# alacritty.toml - Default config with JetBrains Mono Nerd Font

[env]
# Example: TERM variable
TERM = "xterm-256color"

[window]
# Window dimensions (optional, in character columns/rows)
dimensions = { columns = 120, lines = 30 }
# Window startup position (optional)
position = { x = 100, y = 100 }
# Whether window starts maximized
startup_mode = "Windowed"
# Enable/disable window decorations (borders, titlebar)
decorations = "Full"

[font]
# Primary font
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }

# Font size in points
size = 9.0

# Glyph offset (tweak if characters feel misaligned)
offset = { x = 0, y = 0 }

# Line spacing
#line_height = 1.0

[colors]
# Example color scheme (optional)
primary = { background = "#1e1e2e", foreground = "#cdd6f4" }

[scrolling]
# Number of lines in the scrollback buffer
history = 10000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

